const data = [
  {
    id: "1",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Hello!",
  },
  {
    id: "2",
    deleted: false,
    owner: "user2",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Hi!",
  },
  {
    id: "3",
    deleted: true,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "How have you been?",
  },
  {
    id: "4",
    deleted: false,
    owner: "user2",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Pretty good!You?",
  },
  {
    id: "5",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Pretty awesome! So whatcha up to?",
  },
  {
    id: "6",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Been playing Elden Ring myself...",
  },
  {
    id: "7",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Ooh! Love that one!",
  },
  {
    id: "8",
    deleted: false,
    owner: "user2",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Yeah, it's awesome!",
  },
  {
    id: "9",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Have you tried it?",
  },
  {
    id: "10",
    deleted: false,
    owner: "user2",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Nah, not really.",
  },
  {
    id: "11",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Yeah, you've been busy lately.",
  },
  {
    id: "12",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "That's life, I suppose.",
  },
  {
    id: "13",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Sure",
  },
  {
    id: "14",
    deleted: false,
    owner: "user2",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Well, anyway...",
  },
  {
    id: "15",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Yeah, anyway XD",
  },
  {
    id: "16",
    deleted: false,
    owner: "user2",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "How's stuff going besides that?",
  },
  {
    id: "17",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "I dunno, it's fine I guess",
  },
  {
    id: "18",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "More or less",
  },
  {
    id: "19",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Lovely",
  },
  {
    id: "20",
    deleted: false,
    owner: "user2",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Hi!",
  },
  {
    id: "21",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "How have you been?",
  },
  {
    id: "22",
    deleted: false,
    owner: "user2",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: true,
    attachment: null,

    txt: "Pretty good!You?",
  },
  {
    id: "23",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: true,
    attachment: null,

    txt: "Pretty awesome! So whatcha up to?",
  },
  {
    id: "24",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: false,
    attachment: null,

    txt: "Yesterday kinda flew by.",
  },
  {
    id: "25",
    deleted: false,
    owner: "user1",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: true,
    attachment: null,

    txt: "Super fast.",
  },
  {
    id: "26",
    deleted: false,
    owner: "user2",
    hours: 12,
    minutes: 12,
    date: 12,
    month: 12,
    year: 2022,
    edited: true,
    attachment: null,

    txt: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, atque?Lorem ipsum dolor sit amet consectetur adipisicing elit.Magni, nam error soluta aliquam repudiandae dolor. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, atque?Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, nam error soluta aliquam repudiandae dolor.",
  },
];
export default data;
